# Generated by Django 3.1.4 on 2021-07-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210729_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderhome',
            name='link',
            field=models.TextField(max_length=200),
        ),
    ]
